### ISSUE TITLE
Non blocking backdrop

### ISSUE THREAD

**Issue by rmpt** [BenedicteGiraud/react-sliding-side-panel#14] opened 2020-02-14 16:11 UTC
**Is your feature request related to a problem? Please describe.**
Yes, I'm trying to use it along with a map, and I need to move the map while the sidebar is opened.

**Describe the solution you'd like**
An open sidebar with a transparent or non-existent backdrop.

**Describe alternatives you've considered**
Some props option to define if the backdrop should exist/block or not.

**Additional context**
No additional info, should just be configurable because it works well for 80% of the cases, but that specific scenario is a big need.

**Comment by BenedicteGiraud** [comment] 2020-02-19 18:27
Hi @rmpt  !

Thanks for your feedback !
I added a "noBackdrop" prop to the SlidingPanel component to remove the backdrop panel.
example:
```
<SlidingPanel
        type={'left'}
        isOpen={openPanel}
        size={30}
        noBackdrop
>
        <div>
          <div>My Panel Content</div>
          <button onClick={() => setOpenPanel(false)}>close</button>
        </div>
</SlidingPanel>
```

You can install the version 1.0.10 of the package to have the changes.

Thanks again !

**Comment by ippander** [comment] 2020-02-20 13:54
Hi.

When `noBackdrop === true` the panel is always rendered to left.

**Comment by BenedicteGiraud** [comment] 2020-02-20 14:34
Hi @ippander !

Thank you ! This has been fixed in the new version 1.0.11

**Comment by ippander** [comment] 2020-02-20 14:49
Hi BenedicteGiraud

Thank you for your fast reaction :). Unfortunately now the `size` parameter is ignored and the panel fills the whole screen.

**Comment by BenedicteGiraud** [comment] 2020-02-20 15:04
I @ippander,

I can't reproduce your issue, could you send me your code ? (in a codepen for instance)
Also, what's your browser ?

**Comment by rmpt** [comment] 2020-02-22 19:52
hey man, thanks! It's working, but it would be nice if the backdrop is no grey at all.
It let all events pass to back components, but is still with a grey background that looks like the backdrop is there.

**Comment by Raynesz** [comment] 2020-02-24 19:29
im running into the same issue. i managed to fix it by editing the css code in the browser. i just set the "a" value of background-color rgba of ".sliding-panel-container.active" to 0 and it was no longer grey. so if there was any way we can access the css it would be possible to work around it.

EDIT: i tried to edit the .css file in node-modules but changes seem to have no effect. im new to react and node so i might be missing something

**Comment by BenedicteGiraud** [comment] 2020-02-25 13:59
Hey guys !
I removed the background overlay in version 1.0.12

**Closed as completed by BenedicteGiraud** 2020-02-25 13:59 UTC
